# -*- coding: utf-8 -*-
"""preproces-data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNs5akbyQ1oFJTTyJgCO0ttDjKAKv1sR
"""
import pandas as pd
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
tags = pd.read_csv('tags.csv')
print('movies: ', movies.shape)
print('ratings: ', ratings.shape)
print('tags: ', tags.shape)

# movies.head(5)
# ratings.head(5)
# tags.head(5)

# getting the movie title and genre 
df = pd.merge(ratings, movies, on='movieId' , how='left')
df = df.drop('title', axis=1)
# df.head(5)

df['genres'] = df['genres'].str.split('|')
# df.head(5)

tags['tag'] = tags['tag'].str.split('|')
tags.drop('timestamp', axis=1, inplace=True)
# tags.head(5)

tags = tags.groupby(['userId','movieId'])['tag'].apply(lambda x: ','.join(x.astype(str))).reset_index()
# tags.head(5)

df = pd.merge(df, tags, on=['userId','movieId'], how='left')

# df.shape()

df['tag'] = df['tag'].apply(lambda d: d if isinstance(d, list) else [])
df['genres'] = df['genres'].apply(lambda d: d if isinstance(d, list) else [])

# df.head()

"""#### Split into train and test data"""

from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df, test_size=0.2, stratify=df.userId)

train_data = train_data.sort_values(['userId', 'movieId'])
# train_data.head()

test_data = test_data.sort_values(['userId','movieId'])
# test_data.head()

print("""#### Save the dataframes as csv files""")
train_data.to_csv('training_data.csv', index = False)
test_data.to_csv('test_data.csv', index = False)

"""## Pre-process the movie data"""

movies['genres'] = movies['genres'].str.split('|')
movies['genres'] = movies['genres'].apply(lambda d: d if isinstance(d, list) else [])
# movies.head()
movies.to_csv('movies.csv', index = False)

print("finished")
